-- AuraAI — private storage bucket for user-uploaded images.
-- Objects are keyed by `<user_id>/<id>` and served only via short-lived signed
-- URLs generated by the backend (service_role). The bucket is private; a
-- retention job purges objects older than the configured window.

insert into storage.buckets (id, name, public)
values ('aura-uploads', 'aura-uploads', false)
on conflict (id) do nothing;

-- storage.objects has RLS enabled by Supabase. With the bucket private and the
-- backend using service_role, no anon/authenticated policies are added here.
